class Vector3:
    def x(self) -> float: ...
    def y(self) -> float: ...
    def z(self) -> float: ...

class Quaterniond:
    def __init__(self, x: float, y: float, z: float, w: float): ...
    def euler(self) -> Vector3: ...
