class Sensor:
    def name(self) -> str: ...
    def set_topic(self, topic: str) -> None: ...

class Link:
    def sensor_count(self) -> int: ...
    def sensor_by_index(self, index: int) -> Sensor: ...

class Joint:
    def sensor_count(self) -> int: ...
    def sensor_by_index(self, index: int) -> Sensor: ...

class Model:
    def link_count(self) -> int: ...
    def link_by_index(self, index: int) -> Link: ...
    def joint_count(self) -> int: ...
    def joint_by_index(self, index: int) -> Joint: ...

class Root:
    def load(self, path: str) -> None: ...
    def model(self) -> Model: ...
    def to_string(self) -> str: ...
