name: Build Container Images

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    env:
      GAZEBO_VERSION: "harmonic"
      PX4_VERSION: "1.15.0"
      ARDUPILOT_VERSION: "4.5.7"
      UBUNTU_VERSION: "22.04"
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build images
        uses: docker/bake-action@v6
        with:
          targets: multicosim,gazebo,px4,ardupilot
