name: Build Container Images

on:
  push:

env:
  GAZEBO_VERSION: harmonic
  PX4_VERSION: 1.15.0
  ARDUPILOT_VERSION: 4.5.7
  UBUNTU_VERSION: "22.04"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build base image
        id: base
        uses: docker/bake-action@v6
        with:
          push: false
          targets: ubuntu
          set: |
            *.platform=linux/amd64,linux/arm64

      - name: Build MultiCoSim image
        id: multicosim
        depends:
          - base
        uses: docker/bake-action@v6
        with:
          push: false
          targets: multicosim
          set: |
            *.platform=linux/amd64,linux/arm64

      - name: Build Gazebo image
        id: gazebo
        depends:
          - base
        uses: docker/bake-action@v6
        with:
          push: false
          targets: gazebo-ubuntu
          set: |
            *.platform=linux/amd64,linux/arm64

      - name: Build PX4 images
        id: px4
        uses: docker/bake-action@v6
        depends:
          - multicosim
          - gazebo
        with:
          push: false
          targets: px4
          set: |
            *.platform=linux/amd64,linux/arm64

      - name: Build ArduPilot images
        id: ardupilot
        uses: docker/bake-action@v6
        depends:
          - multicosim
          - gazebo
        with:
          push: false
          targets: px4
          set: |
            *.platform=linux/amd64,linux/arm64
